# Generated by Django 5.2.18 on 2026-10-08 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_management", "0023_content_display_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="OasisIndexJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("catalogue_version", models.PositiveIntegerField()),
                ("requested_document_id", models.PositiveIntegerField(null=True)),
                ("requested_folder_id", models.PositiveIntegerField(null=True)),
                ("profile", models.CharField(default="lexical", max_length=16)),
                ("state", models.CharField(default="queued", max_length=16)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("started_on", models.DateTimeField(null=True)),
                ("finished_on", models.DateTimeField(null=True)),
                ("diagnostics", models.TextField(default="")),
                ("documents", models.JSONField(default=list)),
                ("manifest", models.JSONField(default=dict)),
                ("manifest_sha256", models.CharField(max_length=64)),
                ("receipt", models.JSONField(null=True)),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
